name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept Android SDK licenses
      run: |
        mkdir -p "$ANDROID_HOME/licenses"
        echo -e "\n8933bad161af4178b11852feb10044517ae7a685" > "$ANDROID_HOME/licenses/android-sdk-license"
        echo -e "\n84824b00f67132342468bd8b3a72df55174a69b1" >> "$ANDROID_HOME/licenses/android-sdk-license"
        echo -e "\n8398e767562181d14939a7566143c7b1f5e2d11fe65" >> "$ANDROID_HOME/licenses/android-googletv-license"
        echo -e "\n84824b00f67132342468bd8b3a72df55174a69b1" >> "$ANDROID_HOME/licenses/android-sdk-license"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK with Verbose Logging
      run: ./gradlew clean assembleDebug --stacktrace --info

    - name: List Contents of build directory
      run: ls -lR app/build/outputs/

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
