name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # 4️⃣ Make gradlew executable
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # 5️⃣ Build debug APK
      - name: Build APK
        run: ./gradlew clean assembleDebug --stacktrace

      # 6️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
